### ISSUE TITLE
Querformat möglich

### ISSUE THREAD

**Issue by stwolter** [TH-Brandenburg/University-Evaluation-Android#10]
**Beschreibung des Problems:**
- Querformat möglich ansonsten auf Hochformat gezwungen

**Stelle des Problems:**
- Auswahl des Fachbereichs/Studiengang

**Verletzte Heuristik:** 3

**Schweregrad:** 2

**Comment by ketain** [comment]
Obsolet, da betroffene Activity nicht mehr existiert. Hochformat wird in gesamter App durchgesetzt.
