### ISSUE TITLE
Foto-Icon/Button

### ISSUE THREAD

**Issue by stwolter** [TH-Brandenburg/University-Evaluation-Android#13]
**Beschreibung des Problems:**
- Foto-Icon/Button prominenter platzieren

**Stelle des Problems:**
- Fragebogen mit Foto beantworten

**Verletzte Heuristik:** 1

**Schweregrad:** 1

**Comment by ketain** [comment]
Foto Icon jetzt unterhalb des Textfeldes platziert. Dort wor das Foto erscheint.
