### ISSUE TITLE
Show error messages at the beginning if QR-Codes are corrupt

### ISSUE THREAD

**Issue by WulfHeikoBirk** [TH-Brandenburg/University-Evaluation-Android#15]
When I finished my evaluation an error message about an invalid QR-Code appeared and I had to start again. This error message should be at the beginning.

**Comment by ketain** [comment]
Could not be reproduced. Even at the moment of reporting, this should not have been possible except if the evaluation was closed by the tutor beforehand. Curious. Will be closed until someone encounters that bug again.
